services:
  passengers_db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=passengers_db
    volumes:
      - ./passengers_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
  routes_db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=routes_db
    volumes:
      - ./routes_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3307:3306'
  trains_db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=trains_db
    volumes:
      - ./trains_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:3306'
  position_time_db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=position_time_db
    volumes:
      - ./position_time_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3309:3306'
  dl:
    image: python:3.11-slim
    volumes:
      - ./dl:/app
    working_dir: /app
    command: python ingest.py
  onboard_unit:
    image: python:3.11-slim
    volumes:
      - ./onboard_unit:/app
    working_dir: /app
    command: python obu.py
  train_sensor:
    image: python:3.11-slim
    volumes:
      - ./train_sensor:/app
    working_dir: /app
    command: python sensor.py
  brake_actuator:
    image: python:3.11-slim
    volumes:
      - ./brake_actuator:/app
    working_dir: /app
    command: python actuator.py
  balise:
    image: python:3.11-slim
    volumes:
      - ./balise:/app
    working_dir: /app
    command: python balise.py
  passengers_ms:
    build: ./passengers_ms
    ports:
      - '8009:80'
    depends_on:
      - passengers_db
      - routes_db
      - trains_db
      - position_time_db
  routes_ms:
    build: ./routes_ms
    ports:
      - '8010:80'
    depends_on:
      - passengers_db
      - routes_db
      - trains_db
      - position_time_db
  trains_ms:
    build: ./trains_ms
    ports:
      - '8011:80'
    depends_on:
      - passengers_db
      - routes_db
      - trains_db
      - position_time_db
  position_time_ms:
    build: ./position_time_ms
    ports:
      - '8012:80'
    depends_on:
      - passengers_db
      - routes_db
      - trains_db
      - position_time_db
  tickets_ms:
    build: ./tickets_ms
    ports:
      - '8013:80'
    depends_on:
      - passengers_db
      - routes_db
      - trains_db
      - position_time_db
  mas:
    build: ./mas
    ports:
      - '8014:80'
  api_gateway:
    build: ./api_gateway
    ports:
      - '8015:80'
  portal:
    build: ./portal
    ports:
      - '8016:80'
  dashboard:
    build: ./dashboard
    ports:
      - '8017:80'
  driver_interface:
    build: ./driver_interface
    ports:
      - '8018:80'

networks:
  default:
    driver: bridge
